services:
  frontend:
    image: node:18
    command: /bin/bash -c "cd /frontend/s2-analyzer-frontend/;exec /bin/bash"
    user: "1000"
    ports:
      - "5173:5173"
    volumes:
      - ./:/frontend
