services:
  backend:
    image: s2-analyzer-backend
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      LOG_LEVEL: info

  frontend:
    build:
      context: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
