[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dataclass-wizard>=0.35.0",
    "fastapi[standard]>=0.115.12",
    "s2-python>=0.5.0",
    "sqlmodel>=0.0.24",
    "websockets>=13.1",
]
